#!/usr/bin/env bash
set -e

R --vanilla <<RSCRIPT
    devtools::install_version("spatstat.core", version = "2.4-4", repos="https://cloud.r-project.org/")
    devtools::install_version("Seurat", version = "4.0.2", repos="https://cloud.r-project.org/")
    devtools::install_github("satijalab/seurat-data")
    remotes::install_github("satijalab/seurat-wrappers")
    remotes::install_github("drieslab/Giotto",  ref="v1.1.0")
    BiocManager::install("clusterProfiler")
RSCRIPT
